<?php

namespace AppBundle\Repository;

/**
 * ExamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BuyTicketsRepository extends \Doctrine\ORM\EntityRepository
{
}
