<?php

namespace AppBundle\Repository;

/**
 * ExamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConceptRepository extends \Doctrine\ORM\EntityRepository
{
    
    /**
     * @return \Doctrine\DBAL\Query\QueryBuilder
     */
    
    public function createOrderedQueryBuilder()
    {
        return $this->createQueryBuilder('concept')
            ->orderBy('concept.id', 'DESC');
    }
}
