mi_pago:
    resource: "@MiPagoBundle/Resources/config/routing.yml"
    prefix:   /mipago

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

app:
    resource: '@AppBundle/Controller/'
    type: annotation
    options:
        expose: true
