mi_pago:
    resource: "@MiPagoBundle/Resources/config/routing.yml"
    prefix:   /mipago

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

app:
    resource: '@AppBundle/Controller/'
    type: annotation
