doctrine:
    #     dbal:
    #         default_connection: mysql
    #         connections:
    #             mysql:
    #                 driver: pdo_mysql
    #                 host: "%database_host%"
    #                 port: "%database_port%"
    #                 dbname: "%database_name%"
    #                 user: "%database_user%"
    #                 password: "%database_password%"
    #                 charset: UTF8
    #             oracle:
    #                 driver: "%gtwin_database_driver%"
    #                 host: "%gtwin_database_host%"
    #                 port: "%gtwin_database_port%"
    #                 dbname: "%gtwin_database_name%"
    #                 user: "%gtwin_database_user%"
    #                 password: "%gtwin_database_password%"
    #                 charset: "WE8MSWIN1252"

    #         # if using pdo_sqlite as your database driver:
    #         #   1. add the path in parameters.yml
    #         #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
    #         #   2. Uncomment database_path in parameters.yml.dist
    #         #   3. Uncomment next line:
    #         #path: '%database_path%'

    #     orm:
    #         auto_generate_proxy_classes: "%kernel.debug%"
    #         default_entity_manager: mysql
    #         entity_managers:
    #             mysql:
    #                 connection: mysql
    #                 mappings:
    #                     AppBundle: ~
    #                     MiPagoBundle: ~
    #             oracle:
    #                 connection: oracle
    #                 mappings:
    #                     AppBundle: ~

    dbal:
        # configure these for your database server
        default_connection: "mysql"
        connections:
            mysql:
                url: "%env(resolve:DATABASE_URL)%"
                driver: "pdo_mysql"
                server_version: "5.7"
                charset: utf8mb4
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci
            oracle:
                driver: "%env(GTWIN_DATABASE_DRIVER)%"
                host: "%env(GTWIN_DATABASE_HOST)%"
                port: "%env(GTWIN_DATABASE_PORT)%"
                dbname: "%env(GTWIN_DATABASE_NAME)%"
                user: "%env(GTWIN_DATABASE_USER)%"
                password: "%env(GTWIN_DATABASE_PASSWORD)%"
                charset: "WE8MSWIN1252"

    orm:
        default_entity_manager: "mysql"
        auto_generate_proxy_classes: true
        entity_managers:
            mysql:
                connection: mysql
                mappings:
                    App:
                        is_bundle: false
                        type: "annotation"
                        dir: "%kernel.project_dir%/src/Entity"
                        prefix: 'App\Entity'
                        alias: "App"
                    MiPagoBundle:
                        type: "annotation"
                        is_bundle: true
                        prefix: 'MiPago\Bundle\Entity'
                        alias: "MiPagoBundle"
            oracle:
                connection: oracle
                mappings:
                    App:
                        type: "annotation"
                        dir: "%kernel.project_dir%/src/Entity"
                        prefix: 'App\Entity'
                        alias: "App"
        # naming_strategy: doctrine.orm.naming_strategy.underscore
        # auto_mapping: true
